### ISSUE TITLE
Handling error propagation during failed publication

### ISSUE THREAD

**Issue by nu11try** [pact-foundation/pact-js-core#609]
### Software versions

- **OS**: macOS Sequoia 15.4 (24E5206s)
- **Pact Node version**: ^10.18.0 ("@pact-foundation/pact": "^12.4.0")
- **Node Version**: v20.18.1

### Issue Checklist

Please confirm the following:

- [ ] I have upgraded to the latest
- [ ] I have the read the FAQs in the Readme
- [ ] I have triple checked, that there are **no unhandled promises** in my code
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

The pipeline is crashing

### Actual behaviour

The pipeline does not crash

### Steps to reproduce

When embedding a publication in ci/cd gitlab, there is a problem. If the publication fails, the pipeline is still considered "green" and this does not stop further steps.

I use the following code in JS

```
const publisher = require('@pact-foundation/pact-node');
const dotenv = require('dotenv');
const path = require('path');
const process = require('process');

dotenv.config();

const args = process.argv;

let version = '1.0.0';

args.forEach(arg => {
  if (arg.includes('--version')) version = arg.split('--version=')[1];
});

const opts = {
  consumerVersion: version,
  pactFilesOrDirs: [path.resolve(process.cwd(), 'contract_testing/pacts')],
  pactBrokerPassword: process.env.PACT_BROKER_PASSWORD,
  pactBrokerUsername: process.env.PACT_BROKER_USERNAME,
  pactBroker: process.env.PACT_BROKER_URL
};

publisher.publishPacts(opts)
```

I call it in the pipeline like this

```
stages:
  - contract-tests
  - ...


contract-tests:
  stage: contract-tests
  image:
    name: ...
  script:
    - npm run test:pact
    - npm run publish:pact -- --version=$CI_COMMIT_TAG
  rules:
    - if: $SKIP_CONTRACT_TESTS == "true"
      when: never
    - if: $CI_COMMIT_TAG != null

```

And so I was able to achieve a pipeline crash so that the following steps do not pass

```
publisher.publishPacts(opts)
  .then(() => {
    console.log('✅ Pacts successfully published');
  })
  .catch((error) => {
    console.error('❌ Publish failed:', error);
    process.exit(1);
  });
```

Fix - `process.exit(1);`
